FROM java:8
MAINTAINER rajesh.sapkale
COPY spring-petclinic-2.1.0.BUILD-20190206.112318-1.jar /home/spring-petclinic-2.1.0.BUILD-20190206.112318-1.jar
EXPOSE 8080
CMD ["java","-jar","/home/spring-petclinic-2.1.0.BUILD-20190206.112318-1.jar"]
